// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKMUYKIaHdnUFRRVhXg1FnJ4OySfGElxo',
    appId: '1:421191798976:web:ac061bf34c4dc93efa9d25',
    messagingSenderId: '421191798976',
    projectId: 'augbacke',
    authDomain: 'augbacke.firebaseapp.com',
    storageBucket: 'augbacke.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_M1P5iXTZ29l4MxcarqC9_1s-RCHZNjA',
    appId: '1:421191798976:android:862334de0d2ed60dfa9d25',
    messagingSenderId: '421191798976',
    projectId: 'augbacke',
    storageBucket: 'augbacke.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjkDiTE6cWpcd7FeCEJcG0ekrQN4dVfKw',
    appId: '1:421191798976:ios:6147213c033ae4bcfa9d25',
    messagingSenderId: '421191798976',
    projectId: 'augbacke',
    storageBucket: 'augbacke.firebasestorage.app',
    iosBundleId: 'com.example.myFrontendapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjkDiTE6cWpcd7FeCEJcG0ekrQN4dVfKw',
    appId: '1:421191798976:ios:6147213c033ae4bcfa9d25',
    messagingSenderId: '421191798976',
    projectId: 'augbacke',
    storageBucket: 'augbacke.firebasestorage.app',
    iosBundleId: 'com.example.myFrontendapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKMUYKIaHdnUFRRVhXg1FnJ4OySfGElxo',
    appId: '1:421191798976:web:0a121e6a90dc7199fa9d25',
    messagingSenderId: '421191798976',
    projectId: 'augbacke',
    authDomain: 'augbacke.firebaseapp.com',
    storageBucket: 'augbacke.firebasestorage.app',
  );
}
